// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['video']['FileManager']['ChooseDirectory']();
}

export function ChooseFile() {
  return window['go']['video']['FileManager']['ChooseFile']();
}

export function GetFile() {
  return window['go']['video']['FileManager']['GetFile']();
}

export function GetHenlo() {
  return window['go']['video']['FileManager']['GetHenlo']();
}

export function SendProgress(arg1) {
  return window['go']['video']['FileManager']['SendProgress'](arg1);
}

export function SendProgressFake() {
  return window['go']['video']['FileManager']['SendProgressFake']();
}
