// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory():Promise<string>;

export function ChooseFile():Promise<string>;

export function Convert():Promise<string>;

export function GetFile():Promise<any>;

export function GetHenlo():Promise<string>;

export function GetHomeDir():Promise<string>;

export function SendProgress(arg1:number):Promise<void>;

export function SendProgressFake():Promise<void>;
